on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: actionregistry.azurecr.io
        username: ${{ secrets.acr_actionregistry_username }}
        password: ${{ secrets.acr_actionregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/cli" -f  "cli/Dockerfile" -t actionregistry.azurecr.io/danademocluster:${{ github.sha }}
        docker push actionregistry.azurecr.io/danademocluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_danademocluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep danademoclustera51d | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace danademoclustera51d`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: danademoclustera51d
        container-registry-url: actionregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_actionregistry_username }}
        container-registry-password: ${{ secrets.acr_actionregistry_password }}
        secret-name: danademoclusdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: danademoclustera51d
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          actionregistry.azurecr.io/danademocluster:${{ github.sha }}
        imagepullsecrets: |
          danademoclusdockerauth